replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-register
  pullPolicy: Always
deployment:
  managementPort: 8001
env:
  open:
    EUREKA_CLIENT_FETCH_REGISTRY: false
    EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8000
ingress:
  enabled: false
resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
