replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-platform
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 120
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero
env:
  open:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_LABEL: null
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hzero
    SPRING_DATASOURCE_PASSWORD: hzero
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    SPRING_REDIS_HOST: redis.hzero.org
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    SPRING_REDIS_POOL_MAX_IDLE: 50
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    SERVER_UNDERTOW_IO_THREADS: 4
    SERVER_UNDERTOW_WORKER_THREADS: 128
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 12000
    RIBBON_READ_TIMEOUT: 5000
    RIBBON_CONNECT_TIMEOUT: 2000
    HZERO_LOV_SQL_ENABLED: true
    HZERO_LOV_SQL_PUBLIC_API_ENABLED: false
    HZERO_LOV_VALUE_ENABLED: true
    HZERO_PLATFORM_INIT_CACHE: true
    HZERO_PLATFORM_HTTP_PROTOCOL: http
    HZERO_DB_OWNER: null
    HZERO_REGIST_ENTITY_ENABLE: false
    HZERO_OAUTH_PASSWORD_PUBLIC_KEY: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJL0JkqsUoK6kt3JyogsgqNp9VDGDp+t3ZAGMbVoMPdHNT2nfiIVh9ZMNHF7g2XiAa8O8AQWyh2PjMR0NiUSVQMCAwEAAQ==
    HZERO_OAUTH_PASSWORD_PRIVATE_KEY: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAkvQmSqxSgrqS3cnKiCyCo2n1UMYOn63dkAYxtWgw90c1Pad+IhWH1kw0cXuDZeIBrw7wBBbKHY+MxHQ2JRJVAwIDAQABAkB3TKXZcVP6tSSN0UgOjLPxng99Z4xvrWJ1jdHFB7TYyUDcnOtE6GkeeMGxtszYtuZ0m5rN9r8eRvIdVUciXbQhAiEA7WGcLd+cvHHA8xNFrbT78Aq4iYm0TVTS6m05ZEOS328CIQCeetcFV8Kdb+P2Y+yWvMtbyFGhROQIFizvxM3S3TiZrQIhAJLrYPB7f9SaSyOm/+89Htk4qXJmyjM6lrgFFgpaUGL9AiB+pkCr/mSDGOYfA+AQ3rPNl5rUvI9XfxFOVAMAntYayQIhAO0hrnwtng6Ubs+58BN69vAl+sd/xugf0jsHcNgZppAb
    HZERO_RESOURCE_PATTERN: /v1/*,/hzero/*,/hpfm/v1/*,/hpfm/hzero/*
    HZERO_SALES_TEMPLATE_CODE: role/organization/default/template/sales
    HZERO_EXPERTS_TEMPLATE_CODE: role/organization/default/template/experts
    SPRING_PROFILES_ACTIVE: dev
    RIBBON_SERVER_LIST_REFRESH_INTERVAL: 10000
    EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 30
    EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 45
    HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE: 128
    HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE: 256
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8100
  name: hzero-platform
deployment:
  managementPort: 8101
resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
