replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-admin
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 1200
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero
env:
  open:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hzero
    SPRING_DATASOURCE_PASSWORD: hzero
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    SPRING_REDIS_HOST: redis.hzero.org
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    SPRING_REDIS_POOL_MAX_IDLE: 50
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    SERVER_UNDERTOW_IO_THREADS: 4
    SERVER_UNDERTOW_WORKER_THREADS: 128
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    SPRING_BOOT_ADMIN_CLIENT_USERNAME: admin
    SPRING_BOOT_ADMIN_CLIENT_PASSWORD: admin
    SPRING_SECURITY_USER_NAME: admin
    SPRING_SECURITY_USER_PASSWORD: admin
    HZERO_AUTO_REFRESH_PERMISSION_ENABLE: true
    HZERO_AUTO_REFRESH_ROUTE_ENABLE: true
    HZERO_AUTO_REFRESH_SWAGGER_ENABLE: true
    HZERO_METRIC_SYNC_ENABLE: false
    HZERO_TRACE_REDIS_REPORTER_ENABLE: false
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8060
  name: hzero-admin
deployment:
  managementPort: 8061
resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
