replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-gateway
  pullPolicy: Always
deployment:
  managementPort: 8081
env:
  open:
    HZERO_GATEWAY_FILTER_COMMON_REQUEST_CHECK_PROJECT: true
    HZERO_GATEWAY_FILTER_COMMON_REQUEST_CHECK_ORGANIZATION: true
    HZERO_GATEWAY_FILTER_COMMON_REQUEST_ENABLE: true
    HZERO_GATEWAY_FILTER_COLLECT_SPAN_ENABLED: false
    HZERO_GATEWAY_CORS_ALLOWED_ORIGINS: '*'
    HZERO_GATEWAY_CORS_ALLOWED_HEADERS: '*'
    HZERO_GATEWAY_CORS_ALLOWED_METHODS: '*'
    HZERO_GATEWAY_HELPER_ENABLE_JWT_LOG: false
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    SPRING_CLOUD_CONFIG_ENABLED: true
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_REDIS_HOST: 192.168.11.167
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 4
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8080
  name: hzero-org.hzero.gateway
ingress:
  enabled: false
resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
