spring:
  application:
    name: hzero-interface
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_interface?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  redis:
    host: ${SPRING_REDIS_HOST:redis.hzero.org}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:1}
    lettuce:
      pool:
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
  servlet:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://hzero:hzero@mongo.hzero.org:27017/test}
server:
  undertow:
    io-threads: ${SERVER_UNDERTOW_IO_THREADS:4}
    worker-threads: ${SERVER_UNDERTOW_WORKER_THREADS:128}
    buffer-size: ${SERVER_UNDERTOW_BUFFER_SIZE:1024}
    direct-buffers: true
    max-http-post-size: 10485760
    allow-unescaped-characters-in-url: true
feign:
  client:
    config:
      default:
        loggerLevel: ${FEIGN_CLIENT_DEFAULT_LOGGER_LEVEL:basic}
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: ${HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE:100}
      maximumSize: ${HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE:200}
      maxQueueSize: ${HYSTRIX_THREADPOOL_DEFAULT_MAX_QUEUE_SIZE:1000}
      queueSizeRejectionThreshold: ${HYSTRIX_THREADPOOL_DEFAULT_QUEUE_SIZE_REJECTION_THRESHOLD:1000}
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS:40000}
ribbon:
  ReadTimeout: ${RIBBON_READ_TIMEOUT:30000}
  ConnectTimeout: ${RIBBON_CONNECT_TIMEOUT:3000}
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
hzero:
  import:
    init-table: true
  lock:
    pattern: ${HZERO_LOCK_PATTERN:single}
    single-server:
      address: ${HZERO_LOCK_REDIS_HOST:${spring.redis.host}}
      port: ${HZERO_LOCK_REDIS_PORT:${spring.redis.port}}
      database: ${HZERO_LOCK_REDIS_DATABASE:${spring.redis.database}}
      password: ${HZERO_LOCK_REDIS_PASSWORD:}
  scheduler:
    executor-code: HITF_EXECUTOR
  data:
    permission:
      db-owner: ${HZERO_DB_OWNER:}
    change:
      enable: true
  audit:
    operation:
      enable: true
    data:
      enable: true
  boot:
    charge:
      system-num: ${HZERO_CHARGE_SYSTEM_NUM:HZERO_INTERFACE}
  modular:
    enable: false
  resource:
    pattern: ${HZERO_RESOURCE_PATTERN:/v1/*,/hzero/*,/hitf/v1/*,/hitf/hzero/*,/v2/*}
logging:
  level:
    org.apache.ibatis: ${LOG_LEVEL:info}
    io.choerodon: ${LOG_LEVEL:info}
    org.hzero: ${LOG_LEVEL:info}
elasticsearch:
  host: ${ELASTICSEARCH_HOST:elasticsearch.hzero.org}
  port: ${ELASTICSEARCH_PORT:9200}
  schema: ${ELASTICSEARCH_SCHEMA:http}
