replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-scheduler
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 120
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_scheduler?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero
env:
  open:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 30
    EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 45
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_scheduler?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hzero
    SPRING_DATASOURCE_PASSWORD: hzero
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    SPRING_REDIS_HOST: redis.hzero.org
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    SPRING_REDIS_POOL_MAX_IDLE: 50
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 12000
    HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE: 128
    HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE: 256
    RIBBON_READ_TIMEOUT: 5000
    RIBBON_CONNECT_TIMEOUT: 10000
    RIBBON_SERVER_LIST_REFRESH_INTERVAL: 10000
    SERVER_UNDERTOW_IO_THREADS: 4
    SERVER_UNDERTOW_WORKER_THREADS: 128
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    SPRING_PROFILES_ACTIVE: default
    SPRING_CLOUD_CONFIG_LABEL: null
    HZERO_DB_OWNER: null
    HZERO_RESOURCE_PATTERN: /v1/*,/hzero/*,/hsdr/v1/*,/hsdr/hzero/*
    HZERO_EXECUTOR_CODE: HSDR_EXECUTOR
    HZERO_REDIS_QUEUE: true
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8130
  name: hzero-scheduler
deployment:
  managementPort: 8131
resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
