replicaCount: 1
image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-iam-saas
  pullPolicy: Always
preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 1200
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero
env:
  open:
    HZERO_ENABLE_DATA_PERMISSION: true
    HZERO_START_INIT_PASSWORD_POPLICY: true
    HZERO_START_INIT_OPEN_LOGIN_WAY: true
    HZERO_START_INIT_USER: true
    HZERO_START_INIT_LDAP: true
    HZERO_START_INIT_CLIENT: true
    HZERO_START_INIT_DOMAIN: true
    HZERO_START_INIT_FIELD_PERMISSION: true
    HZERO_START_INIT_DOC_AUTH: true
    HZERO_IMPORT_INIT_TABLE: false
    HZERO_CAPTCHA_TEST_DISABLE: false
    TENANT_INIT_ASPECT: false
    HZERO_DB_OWNER: null
    HZERO_PERMISSION_CLEAN_PERMISSION: false
    HZERO_RESOURCE_PATTERN: /v1/*,/hzero/*
    HZERO_PERMISSION_SKIP_PARSE_SERVICES: register,gateway,oauth,swagger
    HZERO_PERMISSION_PARSE_PERMISSION: true
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 30
    EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 45
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hzero
    SPRING_DATASOURCE_PASSWORD: hzero
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000
    SPRING_REDIS_HOST: redis.hzero.org
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_POOL_MAX_WAIT: 5000
    SPRING_REDIS_POOL_MAX_ACTIVE: 50
    SPRING_REDIS_POOL_MAX_IDLE: 50
    HYSTRIX_THREADPOOL_DEFAULT_CORE_SIZE: 128
    HYSTRIX_THREADPOOL_DEFAULT_MAXIMUM_SIZE: 256
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 12000
    RIBBON_READ_TIMEOUT: 5000
    RIBBON_CONNECT_TIMEOUT: 2000
    RIBBON_SERVER_LIST_REFRESH_INTERVAL: 10000
    SERVER_UNDERTOW_IO_THREADS: 4
    SERVER_UNDERTOW_WORKER_THREADS: 128
    SERVER_UNDERTOW_BUFFER_SIZE: 1024
    HZERO_ENABLE_DATA_AUDIT: false
    HZERO_ENABLE_OP_AUDIT: false
    SPRING_PROFILES_ACTIVE: default
    HZERO_ACTUATOR_SHOW_EXECUTOR_INFO: true
    HZERO_IAM_USERNAME_REGEX: ^(((?=.*[0-9])(?=.*[a-zA-Z])|(?=.*[0-9])(?=.*[_-])|(?=.*[a-zA-Z])(?=.*[_-]))[\w-]{6,30
    HZERO_IAM_USER_EMAIL_NULLABLE: true
    HZERO_IAM_USER_PHONE_NULLABLE: true
    HZERO_IAM_LOGIN_PHONE_FORMAT: true
    HZERO_IAM_LOGIN_EMAIL_FORMAT: true
    HZERO_USER_ENABLE_ROOT: false
    HZERO_ENABLE_CACHE: false
    HZERO_DOC_TENANT_TYPE: CUSTOM_TENANT
    SPRING_CLOUD_CONFIG_LABEL: null
    HZERO_FIELD_PERMISSION_ENABLE: true
    HZERO_LOV_SQL_PUBLIC_API_ENABLED: false
    HZERO_REGISTER_URL_ACTIVATE_AES_KEY: RVz3QWIx66c6e-MDhftkIY4UTgqZBia9weaTBJvXt4s=
    LOG_LEVEL: info
    JAVA_OPTS: |
      -Xms1024m -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot
logs:
  parser: spring-boot
persistence:
  enabled: false
service:
  enabled: false
  type: ClusterIP
  port: 8030
  name: hzero-iam
deployment:
  managementPort: 8031
resources:
  limits:
    memory: 1.7Gi
  requests:
    memory: 1.2Gi
