spring:
  application:
    name: hzero-workflow-plus
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_workflow_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}
  redis:
    host: ${SPRING_REDIS_HOST:redis.hzero.org}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:1}
    lettuce:
      pool:
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
  freemarker:
    request-context-attribute: base
    suffix: .html
    content-type: text/html
    cache: true
    template-loader-path: classpath:/static/
    charset: UTF-8
    expose-request-attributes: true
server:
  undertow:
    io-threads: ${SERVER_UNDERTOW_IO_THREADS:4}
    worker-threads: ${SERVER_UNDERTOW_WORKER_THREADS:128}
    buffer-size: ${SERVER_UNDERTOW_BUFFER_SIZE:1024}
    direct-buffers: true
    max-http-post-size: 10485760
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS:40000}
  stream:
    queue:
      enabled: false
ribbon:
  ReadTimeout: ${RIBBON_READ_TIMEOUT:30000}
  ConnectTimeout: ${RIBBON_CONNECT_TIMEOUT:3000}
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
hzero:
  lock:
    pattern: single
    single-server:
      address: ${SPRING_REDIS_HOST:redis.hzero.org}
      port: ${SPRING_REDIS_PORT:6379}
  scheduler:
    executor-code: HWFP_EXECUTOR
  workflow:
    hr-service-name: ${HZERO_WORKFLOW_HR_SERVICE:hzero-platform}
    activiti:
      mail-server-host: ${HZERO_WORKFLOW_MAIL_HOST:stmp.163.com}
      mail-server-port: ${HZERO_WORKFLOW_MAIL_PORT:25}
      mail-server-username: ${HZERO_WORKFLOW_MAIL_USERNAME:hzero@163.com}
      mail-server-password: ${HZERO_WORKFLOW_MAIL_PASSWORD:hzero}
      database-type: ${DATABASE_TYPE:mysql}
    engineUrl: ${HZERO_WORKFLOW_SERVICE_URL:http://dev.hzero.org:8080/hwfp}
  lov:
    sql:
      enabled: true
    value:
      enabled: true
  resource:
    pattern: ${HZERO_RESOURCE_PATTERN:/v1/*,/hzero/*,/hwfp/v1/*,/hwfp/hzero/*}
  modular:
    enable: false
logging:
  level:
    org.hzero.workflow: ${LOG_LEVEL:info}
    org.activiti: ${LOG_LEVEL:info}
